-- Initial schema for Dhaka Tesla Pool.
-- Part 1 is generated by Prisma from prisma/schema.prisma.
-- Part 2 (at the end) is written by hand: CHECK constraints that Prisma cannot express.

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('PASSENGER', 'DRIVER');

-- CreateEnum
CREATE TYPE "Zone" AS ENUM ('BANANI', 'GULSHAN_1', 'GULSHAN_2', 'MOHAKHALI', 'FARMGATE', 'DHANMONDI', 'MIRPUR_10', 'UTTARA', 'BASHUNDHARA');

-- CreateEnum
CREATE TYPE "PoolStatus" AS ENUM ('ACCEPTED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "RequestStatus" AS ENUM ('REQUESTED', 'MATCHED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "MemberStatus" AS ENUM ('ACTIVE', 'LEFT', 'REMOVED');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('CASH');

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('REQUEST_CREATED', 'REQUEST_MATCHED', 'REQUEST_REQUEUED', 'REQUEST_CANCELLED', 'POOL_CREATED', 'DRIVER_ARRIVED', 'POOL_STARTED', 'FARE_LOCKED', 'POOL_COMPLETED', 'POOL_CANCELLED');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" "UserRole" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "driver_profiles" (
    "user_id" UUID NOT NULL,
    "is_online" BOOLEAN NOT NULL DEFAULT false,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "driver_profiles_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "vehicles" (
    "id" UUID NOT NULL,
    "driver_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "capacity" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pools" (
    "id" UUID NOT NULL,
    "vehicle_id" UUID NOT NULL,
    "pickup_zone" "Zone" NOT NULL,
    "status" "PoolStatus" NOT NULL DEFAULT 'ACCEPTED',
    "capacity" SMALLINT NOT NULL,
    "seats_available" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "arrived_at" TIMESTAMPTZ(6),
    "started_at" TIMESTAMPTZ(6),
    "completed_at" TIMESTAMPTZ(6),
    "cancelled_at" TIMESTAMPTZ(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "pools_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ride_requests" (
    "id" UUID NOT NULL,
    "passenger_id" UUID NOT NULL,
    "pickup_zone" "Zone" NOT NULL,
    "dropoff_zone" "Zone" NOT NULL,
    "seats" SMALLINT NOT NULL,
    "status" "RequestStatus" NOT NULL DEFAULT 'REQUESTED',
    "distance_m" INTEGER NOT NULL,
    "estimated_fare_poysha" INTEGER NOT NULL,
    "fare_base_poysha" INTEGER,
    "fare_distance_poysha" INTEGER,
    "fare_discount_poysha" INTEGER,
    "fare_total_poysha" INTEGER,
    "payment_method" "PaymentMethod" NOT NULL DEFAULT 'CASH',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "matched_at" TIMESTAMPTZ(6),
    "started_at" TIMESTAMPTZ(6),
    "completed_at" TIMESTAMPTZ(6),
    "cancelled_at" TIMESTAMPTZ(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ride_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pool_members" (
    "id" UUID NOT NULL,
    "pool_id" UUID NOT NULL,
    "ride_request_id" UUID NOT NULL,
    "status" "MemberStatus" NOT NULL DEFAULT 'ACTIVE',
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "left_at" TIMESTAMPTZ(6),

    CONSTRAINT "pool_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ride_events" (
    "id" BIGSERIAL NOT NULL,
    "pool_id" UUID,
    "ride_request_id" UUID,
    "actor_user_id" UUID,
    "type" "EventType" NOT NULL,
    "from_status" TEXT,
    "to_status" TEXT,
    "data" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ride_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "vehicles_driver_id_key" ON "vehicles"("driver_id");

-- CreateIndex
CREATE INDEX "pools_status_pickup_zone_idx" ON "pools"("status", "pickup_zone");

-- CreateIndex
CREATE INDEX "pools_vehicle_id_created_at_idx" ON "pools"("vehicle_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "pools_one_active_per_vehicle" ON "pools"("vehicle_id") WHERE (status = 'ACCEPTED' OR status = 'DRIVER_ARRIVED' OR status = 'STARTED');

-- CreateIndex
CREATE INDEX "ride_requests_status_pickup_zone_created_at_idx" ON "ride_requests"("status", "pickup_zone", "created_at");

-- CreateIndex
CREATE INDEX "ride_requests_passenger_id_created_at_idx" ON "ride_requests"("passenger_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "ride_requests_one_active_per_passenger" ON "ride_requests"("passenger_id") WHERE (status = 'REQUESTED' OR status = 'MATCHED' OR status = 'IN_PROGRESS');

-- CreateIndex
CREATE INDEX "pool_members_pool_id_status_idx" ON "pool_members"("pool_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "pool_members_pool_id_ride_request_id_key" ON "pool_members"("pool_id", "ride_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "pool_members_one_active_per_request" ON "pool_members"("ride_request_id") WHERE (status = 'ACTIVE');

-- CreateIndex
CREATE INDEX "ride_events_ride_request_id_created_at_idx" ON "ride_events"("ride_request_id", "created_at");

-- CreateIndex
CREATE INDEX "ride_events_pool_id_created_at_idx" ON "ride_events"("pool_id", "created_at");

-- AddForeignKey
ALTER TABLE "driver_profiles" ADD CONSTRAINT "driver_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "driver_profiles"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pools" ADD CONSTRAINT "pools_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ride_requests" ADD CONSTRAINT "ride_requests_passenger_id_fkey" FOREIGN KEY ("passenger_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pool_members" ADD CONSTRAINT "pool_members_pool_id_fkey" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pool_members" ADD CONSTRAINT "pool_members_ride_request_id_fkey" FOREIGN KEY ("ride_request_id") REFERENCES "ride_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ride_events" ADD CONSTRAINT "ride_events_pool_id_fkey" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ride_events" ADD CONSTRAINT "ride_events_ride_request_id_fkey" FOREIGN KEY ("ride_request_id") REFERENCES "ride_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ride_events" ADD CONSTRAINT "ride_events_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- =============================================================================
-- Part 2 · Hand-written CHECK constraints (the database-level "backstop")
-- Even if application code had a bug, PostgreSQL refuses rows that break these rules.
-- =============================================================================

-- Emails are stored lowercase, so "Nusrat@..." and "nusrat@..." can never be two accounts.
ALTER TABLE "users"
  ADD CONSTRAINT "users_email_lowercase" CHECK ("email" = lower("email"));

-- A Tesla has between 1 and 6 seats (Bullet has 3).
ALTER TABLE "vehicles"
  ADD CONSTRAINT "vehicles_capacity_range" CHECK ("capacity" BETWEEN 1 AND 6);

-- The seat counter can never go below 0 or above the pool's capacity: overbooking is impossible.
ALTER TABLE "pools"
  ADD CONSTRAINT "pools_capacity_positive" CHECK ("capacity" >= 1),
  ADD CONSTRAINT "pools_seats_available_range" CHECK ("seats_available" BETWEEN 0 AND "capacity");

ALTER TABLE "ride_requests"
  -- A ride must go somewhere.
  ADD CONSTRAINT "ride_requests_pickup_differs_from_dropoff" CHECK ("pickup_zone" <> "dropoff_zone"),
  -- 1 to 3 seats per request.
  ADD CONSTRAINT "ride_requests_seats_range" CHECK ("seats" BETWEEN 1 AND 3),
  ADD CONSTRAINT "ride_requests_distance_positive" CHECK ("distance_m" > 0),
  ADD CONSTRAINT "ride_requests_estimate_non_negative" CHECK ("estimated_fare_poysha" >= 0),
  -- The final fare is written all at once (when the trip starts) or not at all.
  ADD CONSTRAINT "ride_requests_fare_all_or_nothing" CHECK (
    ("fare_base_poysha" IS NULL AND "fare_distance_poysha" IS NULL
      AND "fare_discount_poysha" IS NULL AND "fare_total_poysha" IS NULL)
    OR
    ("fare_base_poysha" IS NOT NULL AND "fare_distance_poysha" IS NOT NULL
      AND "fare_discount_poysha" IS NOT NULL AND "fare_total_poysha" IS NOT NULL)
  ),
  -- Money is never negative, and the breakdown always adds up.
  ADD CONSTRAINT "ride_requests_fare_non_negative" CHECK (
    "fare_base_poysha" >= 0 AND "fare_distance_poysha" >= 0
    AND "fare_discount_poysha" >= 0 AND "fare_total_poysha" >= 0
  ),
  ADD CONSTRAINT "ride_requests_fare_adds_up" CHECK (
    "fare_total_poysha" = "fare_base_poysha" + "fare_distance_poysha" - "fare_discount_poysha"
  );

-- Every history row must be about a pool, a ride request, or both.
ALTER TABLE "ride_events"
  ADD CONSTRAINT "ride_events_has_subject" CHECK ("pool_id" IS NOT NULL OR "ride_request_id" IS NOT NULL);
